name       : xerces-c
version    : 3.2.1
release    : 3
source     :
    - https://github.com/apache/xerces-c/archive/Xerces-C_3_2_1.tar.gz : 7c2e11a2dc4c94000ec65853003433682ea8f0aa60c123c81d7f5d2001cf60bf
license    : Apache-2.0
component  : system.utils
libsplit   : no
summary    : Xerces-C++ is a validating XML parser written in a portable subset of C++
description: |
    Xerces-C++ makes it easy to give your application the ability to read and write XML data. A shared library is provided for parsing, generating, manipulating, and validating XML documents using the DOM, SAX, and SAX2 APIs.
builddeps  :
    - pkgconfig(libcurl)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
