name       : xerces-c
version    : 3.2.3
release    : 4
source     :
    - https://github.com/apache/xerces-c/archive/refs/tags/v3.2.3.tar.gz : a7cf582d618c048ef6a4684457a641940179c446e5f02c81f582f5952755a76a
license    : Apache-2.0
component  : system.utils
libsplit   : no
summary    : Xerces-C++ is a validating XML parser written in a portable subset of C++
description: |
    Xerces-C++ makes it easy to give your application the ability to read and write XML data. A shared library is provided for parsing, generating, manipulating, and validating XML documents using the DOM, SAX, and SAX2 APIs.
builddeps  :
    - pkgconfig(libcurl)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
